"""fix

Revision ID: 548a0a42d02a
Revises: b7e44c457eec
Create Date: 2022-09-27 17:32:04.584584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548a0a42d02a'
down_revision = 'b7e44c457eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_authors_name', table_name='authors')
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    op.create_index('ix_authors_name', 'authors', ['name'], unique=False)
    # ### end Alembic commands ###
