"""fix 2

Revision ID: 83e628fe2235
Revises: 548a0a42d02a
Create Date: 2022-09-27 17:51:08.508198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83e628fe2235'
down_revision = '548a0a42d02a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('authors_ibfk_1', 'authors', type_='foreignkey')
    op.drop_column('authors', 'book_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('authors_ibfk_1', 'authors', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###
