"""Initial migration

Revision ID: c8c099f4a4e5
Revises: 
Create Date: 2025-05-22 10:13:44.580897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8c099f4a4e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_index('email', table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=32), nullable=True))
    op.create_index('email', 'users', ['email'], unique=False)
    op.create_table('products',
    sa.Column('product_id', mysql.SMALLINT(), autoincrement=True, nullable=False),
    sa.Column('category', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('prod_name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
